apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-converter.fullname" . }}
  labels:
    {{- include "image-converter.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true, "exposed_ports": {"80":{}}}' # using GKE NEG
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "image-converter.selectorLabels" . | nindent 4 }}
